name: env-electron-python
channels:
- defaults
- conda-forge
dependencies:
- python = 3.6
- PyInstaller = 3.5
- pywin32 = 223
- nodejs = 10.13.0
- git = 2.20.1
- pip
- pip:
  - pandas == 0.25.2
  - openpyxl == 3.0.0
  - zerorpc == 0.6.3
  - blackfynn == 4.0.1
  - configparser == 4.0.2
  - python-docx == 0.8.10
  - xlrd == 1.2.0
