name:  env-electron-python
channels:
  - defaults
  - conda-forge
dependencies:
- python = 3.9.7
- PyInstaller
- nodejs = 18.16.0
- git = 2.20.1
- pip
- pip:
  - chardet == 4.0.0
  - pandas == 1.4.2
  - openpyxl == 3.0.10
  - configparser == 4.0.2
  - python-docx == 0.8.10
  - xlrd == 2.0.1
  - biopython == 1.79
  - gevent == 21.12.0
  - certifi
  - flask == 2.0.2
  - flask_restx
  - flask-cors == 4.0.0
  - werkzeug == 2.0.2
  - opencv-python == 4.5.3.56
  - grpcio
  - tqdm 
  - numpy == 1.23.0
  - protobuf == 4.21.12
  - pennsieve2 == 0.1.1
  - boto3
  - jsonschema == 4.17.3
  - urllib3 == 2.0.6
  - requests == 2.31.0
  - backports.tarfile
  - setuptools == 71.0.4
  - pysoda-fairdataihub-tools == 0.1.36