name: env-electron-python
channels:
- defaults
- conda-forge
dependencies:
- python = 3.9
- PyInstaller = 4.7
- nodejs = 10.13.0
- libgcc = 7.2.0
- git = 2.20.1
- pip
- pip:
  - chardet == 4.0.0
  - pandas == 1.4.2
  - openpyxl == 3.0.3
  - pennsieve == 6.1.2
  - configparser == 4.0.2
  - python-docx == 0.8.10
  - xlrd == 1.2.0
  - biopython == 1.79
  - flask == 2.0.2
  - flask_restx
  - protobuf == 3.20.0
  - gevent == 21.12.0
<<<<<<< .merge_file_GpiYiT
  - werkzeug == 2.0.2
  - opencv-python == 4.6.0.66
=======
  - werkzeug == 2.0.2
>>>>>>> .merge_file_bw1Rdn
