name: env-electron-python
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - expat=2.5.0
  - libffi=3.4.4
  - nodejs=20.8.0
  - openssl=1.1.1w
  - pip=23.2.1
  - python=3.9.7
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
    - altgraph==0.17.4
    - aniso8601==9.0.1
    - attrs==23.1.0
    - biopython==1.79
    - boto3==1.28.63
    - botocore==1.31.63
    - certifi==2023.7.22
    - cffi==1.16.0
    - chardet==4.0.0
    - charset-normalizer==3.3.0
    - click==8.1.7
    - colorama==0.4.6
    - configparser==4.0.2
    - et-xmlfile==1.1.0
    - flask==2.0.2
    - flask-cors==4.0.0
    - flask-restx==1.1.0
    - futures==3.1.1
    - gevent==21.12.0
    - greenlet==1.1.3.post0
    - grpcio==1.50.0
    - grpcio-tools==1.50.0
    - idna==3.4
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - jmespath==1.0.1
    - jsonschema==4.17.3
    - jsonschema-specifications==2023.7.1
    - lxml==4.9.3
    - markupsafe==2.1.3
    - numpy==1.23.0
    - opencv-python==4.5.3.56
    - openpyxl==3.0.9
    - pandas==1.4.2
    - pefile==2023.2.7
    - pennsieve2==0.1.1
    - protobuf==4.21.12
    - pycparser==2.21
    - python-dateutil==2.8.2
    - pytz==2021.3
    - requests==2.31.0
    - six==1.16.0
    - pyinstaller==4.7
    - python-docx==0.8.10
    - pyrsistent==0.19.3
    - pywin32-ctypes==0.2.2
    - referencing==0.30.2
    - rpds-py==0.10.6
    - s3transfer==0.7.0
    - tqdm==4.66.1
    - urllib3==1.26.7
    - werkzeug==2.0.2
    - xlrd==2.0.1
    - pyinstaller-hooks-contrib==2023.10
    - zope-event==5.0
    - zope-interface==6.1
    - setuptools == 71.0.4
    - backports.tarfile

