name: env-validator-electron-python
channels:
- defaults
- conda-forge
dependencies:
- python = 3.7.0
- PyInstaller = 4.9
- nodejs = 10.13.0
- pywin32 = 223
- git = 2.20.1
- pip
- pip:
  - chardet == 4.0.0
  - pandas == 0.25.2
  - openpyxl == 3.0.0
  - zerorpc == 0.6.3
  - pennsieve == 6.1.2
  - configparser == 4.0.2
  - python-docx == 0.8.10
  - xlrd == 1.2.0
  - biopython == 1.78
  - flask == 2.0.2